// frontend-angular/src/app/pages/events-list/events-list.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { EventsService } from '../../services/events.service';
import { EventModel } from '../../models/event.model';

@Component({
  selector: 'app-events-list',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  templateUrl: './events-list.component.html',
  styleUrl: './events-list.component.css'
})
export class EventsListComponent implements OnInit {
  events: EventModel[] = [];
  loading = false;
  message = '';
  messageType: 'success' | 'danger' | '' = '';

  page = 1;
  limit = 6;
  totalPages = 1;
  total = 0;
  search = '';
  categoria = '';

  constructor(private eventsService: EventsService) {}

  ngOnInit(): void {
    this.loadEvents();
  }

  loadEvents(): void {
    this.loading = true;
    this.eventsService
      .getEvents({ page: this.page, limit: this.limit, categoria: this.categoria || undefined, q: this.search || undefined })
      .subscribe({
        next: (response) => {
          this.events = response.data;
          this.total = response.meta.total;
          this.totalPages = response.meta.totalPages || 1;
          this.loading = false;
        },
        error: () => {
          this.loading = false;
          this.message = 'No se pudieron cargar los eventos.';
          this.messageType = 'danger';
        }
      });
  }

  applyFilters(): void {
    this.page = 1;
    this.loadEvents();
  }

  clearFilters(): void {
    this.search = '';
    this.categoria = '';
    this.applyFilters();
  }

  changePage(delta: number): void {
    const nextPage = this.page + delta;
    if (nextPage < 1 || nextPage > this.totalPages) {
      return;
    }
    this.page = nextPage;
    this.loadEvents();
  }

  deleteEvent(id?: string): void {
    if (!id) {
      return;
    }
    this.loading = true;
    this.eventsService.deleteEvent(id).subscribe({
      next: (response) => {
        this.message = response.message;
        this.messageType = 'success';
        this.loadEvents();
      },
      error: () => {
        this.loading = false;
        this.message = 'No se pudo eliminar el evento.';
        this.messageType = 'danger';
      }
    });
  }
}

<div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3 mb-4">
  <div>
    <h1 class="h3 mb-1">Eventos</h1>
    <p class="text-muted mb-0">Gestiona y filtra los eventos registrados.</p>
  </div>
  <a class="btn btn-primary" routerLink="/eventos/nuevo">Crear evento</a>
</div>

<div class="row g-3 mb-4">
  <div class="col-md-4">
    <div class="card border-0 shadow-sm h-100">
      <div class="card-body">
        <p class="text-muted mb-1">Total de eventos</p>
        <h3 class="fw-bold mb-0">{{ total }}</h3>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card border-0 shadow-sm h-100">
      <div class="card-body">
        <p class="text-muted mb-1">Filtros activos</p>
        <h3 class="fw-bold mb-0">{{ (search || categoria) ? 'Sí' : 'No' }}</h3>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card border-0 shadow-sm h-100">
      <div class="card-body">
        <p class="text-muted mb-1">Páginas</p>
        <h3 class="fw-bold mb-0">{{ totalPages }}</h3>
      </div>
    </div>
  </div>
</div>

<div class="card shadow-sm mb-4">
  <div class="card-body">
    <div class="row g-3">
      <div class="col-md-5">
        <label class="form-label">Buscar por título</label>
        <input class="form-control" [(ngModel)]="search" placeholder="Ej. Festival" />
      </div>
      <div class="col-md-4">
        <label class="form-label">Categoría</label>
        <input class="form-control" [(ngModel)]="categoria" placeholder="Ej. Música" />
      </div>
      <div class="col-md-3 d-flex align-items-end gap-2">
        <button class="btn btn-outline-primary w-100" (click)="applyFilters()">Filtrar</button>
        <button class="btn btn-outline-secondary w-100" (click)="clearFilters()">Limpiar</button>
      </div>
    </div>
  </div>
</div>

<div *ngIf="message" class="alert" [ngClass]="'alert-' + messageType">{{ message }}</div>

<div *ngIf="loading" class="text-center my-4">
  <div class="spinner-border text-primary" role="status"></div>
  <div class="mt-2">Cargando eventos...</div>
</div>

<div class="table-responsive" *ngIf="!loading">
  <table class="table table-hover align-middle">
    <thead>
      <tr>
        <th>Título</th>
        <th>Categoría</th>
        <th>Fecha</th>
        <th>Precio</th>
        <th>Estado</th>
        <th class="text-end">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let evento of events">
        <td>{{ evento.titulo }}</td>
        <td>{{ evento.categoria }}</td>
        <td>{{ evento.fecha | date: 'mediumDate' }}</td>
        <td>{{ evento.precio | currency: 'EUR' }}</td>
        <td>
          <span class="badge" [ngClass]="evento.esPublico ? 'bg-success' : 'bg-secondary'">
            {{ evento.esPublico ? 'Público' : 'Privado' }}
          </span>
        </td>
        <td class="text-end">
          <a class="btn btn-sm btn-outline-primary me-2" [routerLink]="['/eventos', evento._id]">Ver</a>
          <a class="btn btn-sm btn-outline-secondary me-2" [routerLink]="['/eventos', evento._id, 'editar']">Editar</a>
          <button class="btn btn-sm btn-outline-danger" (click)="deleteEvent(evento._id)">Eliminar</button>
        </td>
      </tr>
      <tr *ngIf="events.length === 0">
        <td colspan="6" class="text-center text-muted">No hay eventos disponibles.</td>
      </tr>
    </tbody>
  </table>
</div>

<nav class="d-flex justify-content-between align-items-center">
  <button class="btn btn-outline-secondary" (click)="changePage(-1)" [disabled]="page <= 1">Anterior</button>
  <span class="text-muted">Página {{ page }} de {{ totalPages }}</span>
  <button class="btn btn-outline-secondary" (click)="changePage(1)" [disabled]="page >= totalPages">Siguiente</button>
</nav>

// frontend-react/src/pages/EventsList.jsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { deleteEvent, fetchEvents } from '../api/eventsApi';

const EventsList = () => {
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);
  const [search, setSearch] = useState('');
  const [categoria, setCategoria] = useState('');

  const loadEvents = async () => {
    setLoading(true);
    try {
      const response = await fetchEvents({ page, limit: 6, categoria, q: search });
      setEvents(response.data);
      setTotalPages(response.meta.totalPages || 1);
  setTotal(response.meta.total || 0);
    } catch (error) {
      setMessage(error.message);
      setMessageType('danger');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadEvents();
  }, [page]);

  const handleFilter = () => {
    setPage(1);
    loadEvents();
  };

  const clearFilter = () => {
    setSearch('');
    setCategoria('');
    setPage(1);
    loadEvents();
  };

  const handleDelete = async (id) => {
    setLoading(true);
    try {
      const response = await deleteEvent(id);
      setMessage(response.message);
      setMessageType('success');
      await loadEvents();
    } catch (error) {
      setMessage(error.message);
      setMessageType('danger');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <div className="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3 mb-4">
        <div>
          <h1 className="h3 mb-1">Eventos</h1>
          <p className="text-muted mb-0">Gestiona y filtra los eventos registrados.</p>
        </div>
        <Link className="btn btn-primary" to="/eventos/nuevo">
          Crear evento
        </Link>
      </div>

      <div className="row g-3 mb-4">
        <div className="col-md-4">
          <div className="card border-0 shadow-sm h-100">
            <div className="card-body">
              <p className="text-muted mb-1">Total de eventos</p>
              <h3 className="fw-bold mb-0">{total}</h3>
            </div>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card border-0 shadow-sm h-100">
            <div className="card-body">
              <p className="text-muted mb-1">Filtros activos</p>
              <h3 className="fw-bold mb-0">{search || categoria ? 'Sí' : 'No'}</h3>
            </div>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card border-0 shadow-sm h-100">
            <div className="card-body">
              <p className="text-muted mb-1">Páginas</p>
              <h3 className="fw-bold mb-0">{totalPages}</h3>
            </div>
          </div>
        </div>
      </div>

      <div className="card shadow-sm mb-4">
        <div className="card-body">
          <div className="row g-3">
            <div className="col-md-5">
              <label className="form-label">Buscar por título</label>
              <input className="form-control" value={search} onChange={(e) => setSearch(e.target.value)} />
            </div>
            <div className="col-md-4">
              <label className="form-label">Categoría</label>
              <input className="form-control" value={categoria} onChange={(e) => setCategoria(e.target.value)} />
            </div>
            <div className="col-md-3 d-flex align-items-end gap-2">
              <button className="btn btn-outline-primary w-100" onClick={handleFilter}>
                Filtrar
              </button>
              <button className="btn btn-outline-secondary w-100" onClick={clearFilter}>
                Limpiar
              </button>
            </div>
          </div>
        </div>
      </div>

      {message && <div className={`alert alert-${messageType}`}>{message}</div>}

      {loading && (
        <div className="text-center my-4">
          <div className="spinner-border text-primary" role="status"></div>
          <div className="mt-2">Cargando eventos...</div>
        </div>
      )}

      {!loading && (
        <div className="table-responsive">
          <table className="table table-hover align-middle">
            <thead>
              <tr>
                <th>Título</th>
                <th>Categoría</th>
                <th>Fecha</th>
                <th>Precio</th>
                <th>Estado</th>
                <th className="text-end">Acciones</th>
              </tr>
            </thead>
            <tbody>
              {events.map((evento) => (
                <tr key={evento._id}>
                  <td>{evento.titulo}</td>
                  <td>{evento.categoria}</td>
                  <td>{new Date(evento.fecha).toLocaleDateString()}</td>
                  <td>€ {evento.precio.toFixed(2)}</td>
                  <td>
                    <span className={`badge ${evento.esPublico ? 'bg-success' : 'bg-secondary'}`}>
                      {evento.esPublico ? 'Público' : 'Privado'}
                    </span>
                  </td>
                  <td className="text-end">
                    <Link className="btn btn-sm btn-outline-primary me-2" to={`/eventos/${evento._id}`}>
                      Ver
                    </Link>
                    <Link className="btn btn-sm btn-outline-secondary me-2" to={`/eventos/${evento._id}/editar`}>
                      Editar
                    </Link>
                    <button className="btn btn-sm btn-outline-danger" onClick={() => handleDelete(evento._id)}>
                      Eliminar
                    </button>
                  </td>
                </tr>
              ))}
              {events.length === 0 && (
                <tr>
                  <td colSpan="6" className="text-center text-muted">
                    No hay eventos disponibles.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}

      <nav className="d-flex justify-content-between align-items-center">
        <button className="btn btn-outline-secondary" onClick={() => setPage((prev) => Math.max(prev - 1, 1))} disabled={page <= 1}>
          Anterior
        </button>
        <span className="text-muted">Página {page} de {totalPages}</span>
        <button
          className="btn btn-outline-secondary"
          onClick={() => setPage((prev) => Math.min(prev + 1, totalPages))}
          disabled={page >= totalPages}
        >
          Siguiente
        </button>
      </nav>
    </div>
  );
};

export default EventsList;
